services:
  asr-app:
    container_name: asr-app 
    build:
      context: .
      dockerfile: Dockerfile
    image: alirezafazli29/asr:dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8003:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
